# Generated by Django 5.2.17 on 2026-09-25 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitsunerobotics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(max_length=500, upload_to="blog/uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
